create table sensor (
                        id int primary key generated by default as identity,
                        name varchar(30) unique not null
);

create table measurements
(
    id           int primary key generated by default as identity,
    value        real not null,
    raining      bool not null,
    fk_sensor_id int not null ,
    foreign key (fk_sensor_id) references sensor (id) on delete CASCADE
);
